name: 9now Token Update Scheduler

on:
  schedule:
    # Runs at 00:00 and 12:00 UTC every day
    - cron: '0 1,13 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update_tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run token update script
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run:
          python 9now.py
