name: Daily Live Channel URL Refresh

on:
  # Allow manual run from GitHub Actions UI
  workflow_dispatch:

  # Run daily at 00:10 UTC (morning AEST/AEDT)
  schedule:
    - cron: '10 0 * * *'

jobs:
  update-channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute All-Channel Redirect URL Updater
        run: python osfa.py
        env:
          # Your script uses GH_TOKEN for GitHub API authentication.
          # Create a repository secret called GH_PAT containing a PAT with `repo` scope.
          GH_TOKEN: ${{ secrets.GH_PAT }}
